"""drop_runtime_from_watched_movies

Revision ID: 7e70548ff405
Revises: e44d43a37e65
Create Date: 2026-03-28 10:51:12.958142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7e70548ff405'
down_revision: Union[str, None] = 'e44d43a37e65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('watched_movies', 'runtime')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('watched_movies', sa.Column('runtime', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
