"""create watched_movies table

Revision ID: e44d43a37e65
Revises: 
Create Date: 2026-03-27 17:43:19.530324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e44d43a37e65'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('watched_movies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tmdb_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('runtime', sa.Integer(), nullable=True),
    sa.Column('my_rating', sa.Integer(), nullable=True),
    sa.Column('my_overview', sa.Text(), nullable=True),
    sa.Column('my_date_watched', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('watched_movies')
    # ### end Alembic commands ###
